name: SignChestShop
main: net.skycraftmc.SignChestShop.SignChestShopPlugin
version: 1.2.4
author: Technius
depend: [Vault]
commands:
    signchestshop:
         description: SignChestShop commands
         usage: /signchestshop <args>
         aliases: [scs]